import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageCode = "en" | "hi" | "kn" | "te";

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navbar / Global
    brandName: "EmpoWork",
    online: "ONLINE",
    offline: "OFFLINE",
    simulateNoSignal: "Simulate No Signal",
    reconnectToCloud: "Reconnect to Cloud",
    networkSyncPortal: "Network & Sync Portal",
    connectedLiveSync: "Connected & Live Syncing",
    localStorageMode: "Local Storage Mode",
    excellentCoverage: "Your digital footprint (attendance logs, check-ins, job requests, and payments) is synced live with the secure cloud registry.",
    noReceptionDetected: "No reception detected. All attendance check-ins, payments, and disputes are stored securely inside your local database and will instant-sync when you regain reception.",
    connectionControl: "Connection Control Simulator:",
    loginRegister: "Login / Register",
    logout: "Logout",
    profile: "Profile",

    // Role-specific Nav Tabs
    workerDashboard: "Worker Space",
    findJobs: "Find Jobs",
    findJobsDesc: "Find verified local daily-wage jobs",
    myApplications: "My Applications",
    checkInRegister: "Check-In & Attendance",
    checkInRegisterDesc: "Log attendance & track daily wages",
    grievances: "Grievances",
    grievancesDesc: "Lodge and track wage/work disputes",
    financialSavings: "Savings & Wages",
    skillCoach: "Skill Coach",
    skillCoachDesc: "AI-guided trade skill development",
    helpFaq: "Help & FAQ",
    helpFaqDesc: "View safety lists & instructions",

    employerDashboard: "Contractor Space",
    postJob: "Post a Job",
    manageJobs: "Manage Jobs",
    manageJobsDesc: "Post and manage job assignments",
    reviewApplications: "Applications",
    reviewApplicationsDesc: "Verify applicants & hire workforce",
    payoutHistory: "Payout Logs",

    adminDashboard: "Welfare Portal",
    platformOverview: "Platform Overview",
    platformOverviewDesc: "Analytics, users & sync status",
    workerRegistry: "Worker Registry",
    employerRegistry: "Employer Registry",
    platformDisputes: "Platform Disputes",
    platformDisputesDesc: "Mediate disputes with AI screening",

    // Landing Page Hero
    empoweringDailyWorkers: "Empowering Daily Wage Workers with AI",
    heroTitle: "Connecting Daily Earners with Fair Employment",
    heroSubtitle: "EmpoWork is a smart digital ecosystem designed for local workers, construction builders, and welfare officers. Register skills, search verified local jobs, log attendance, and receive secure daily wages.",
    getStartedButton: "Get Started Now",
    openWelfareOfficerPortal: "Open Welfare Admin Portal",
    whyChooseEmpowork: "Why Choose EmpoWork?",
    howItWorks: "How It Works",
    empoweringFeatures: "Empowering Features",
    disclaimerText: "Note: Real-time payments are securely processed and backed by the Ministry of Labor guidelines.",

    // Landing Features
    geoAttendanceTitle: "Verified Geo-Attendance",
    geoAttendanceDesc: "Interactive spatial validation for daily arrivals, preventing timing and payroll discrepancies.",
    instantWageTitle: "Secure Digital Wallets",
    instantWageDesc: "Transparent same-day payment logs ensuring fair pay directly credited into savings wallets.",
    geminiAdvisorTitle: "Gemini AI Dispute Resolution",
    geminiAdvisorDesc: "Neutral automated screening and professional mediation suggestion systems for daily labor disputes.",
    regionalVoiceTitle: "Multilingual Voice Input",
    regionalVoiceDesc: "Allows workers to record profiles, register applications, and lodge disputes in Hindi, Kannada, or English.",
    tradeJobsAvailable: "Trade Jobs Available",
    applyForHighPayingWages: "Apply for high-paying verification-backed daily wages",
    attendanceWagesSavingsHub: "Attendance, Wages & Savings Hub",
    verifyShiftsDesc: "Verify your shifts, track your paycheck history, and plan your financial future",
    shiftsAndLogs: "Shifts & Logs",
    savingsAndGoals: "Savings & Goals",
    employerFeedback: "Employer Feedback & Endorsements",
    officialRatingsDesc: "Official ratings and commendations submitted by verified builder contractors upon job completion.",
    noJobsFound: "No jobs found matching filters.",
    tryChangingFilters: "Try changing your trade selection or keyword!",
    quickApply: "Quick Apply with Trade Profile",
    quickContact: "Quick Contact Builder",
    statusPending: "Status: PENDING",
    statusAccepted: "Status: ACCEPTED",
    statusRejected: "Status: REJECTED",
    gpsTracker: "GPS Tracker",
    accessingGps: "Accessing Satellite GPS...",
    activeLat: "Active Lat",
    gpsOff: "GPS Off (Click to activate)",
    safetyChecklistTitle: "Safety Checklist & Clearance",
    submitJobApplication: "Submit Job Application",
    searchJobsPlaceholder: "Search Jobs...",
    postNewJob: "Post a New Job Assignment",
    managePostedJobs: "Manage Posted Assignments",
    reviewApplicationsTitle: "Review Applications",
    payoutLogsTitle: "Payout Logs & Wallet Transfer",
    welfareDisputesTitle: "Welfare Disputes & Grievances",
    tradeRoleRequired: "Trade Role required",
    estimatedWage: "Estimated Daily Wage",
    numberOfSlots: "Number of Slots",
    jobLocation: "Job Location",
    jobDescription: "Job Description",
    createJobAssignment: "Create Job Assignment",
    preshiftSafetyTitle: "Pre-Shift Safety Briefing",
    financialCoachTitle: "AI Financial Coach & Savings Planner",
    disputeCenterTitle: "Welfare Dispute Center",
    dashboard: "Dashboard",
    dashboardDesc: "Overview & metrics",
    myProfile: "My Profile",
    myProfileDesc: "Manage your details",
    myApplicationsDesc: "Track applications",
    attendance: "Attendance",
    attendanceDesc: "Check-in & logs",
    myEarnings: "My Earnings",
    myEarningsDesc: "Wages & savings",
    skillDevelopment: "Skill Development",
    skillDevelopmentDesc: "AI Skill Coach & tutorials",
    myTools: "My Tools",
    myToolsDesc: "Trade equipment",
    notifications: "Notifications",
    notificationsDesc: "Unread updates & alerts",
    complaintsSupport: "Complaints & Support",
    complaintsSupportDesc: "Lodge & track disputes",
    settings: "Settings",
    settingsDesc: "Preferences & setup",
    logoutDesc: "Sign out of session"
  },
  hi: {
    // Navbar / Global
    brandName: "एम्पोवर्क",
    online: "ऑनलाइन",
    offline: "ऑफ़लाइन",
    simulateNoSignal: "सिग्नल न होने का अनुकरण करें",
    reconnectToCloud: "क्लाउड से पुनः कनेक्ट करें",
    networkSyncPortal: "नेटवर्क और सिंक पोर्टल",
    connectedLiveSync: "कनेक्टेड और लाइव सिंक हो रहा है",
    localStorageMode: "स्थानीय संग्रहण मोड",
    excellentCoverage: "आपका डिजिटल पदचिह्न (उपस्थिति लॉग, चेक-इन, नौकरी के अनुरोध और भुगतान) सुरक्षित क्लाउड रजिस्ट्री के साथ लाइव सिंक किया जाता है।",
    noReceptionDetected: "कोई सिग्नल नहीं मिला। सभी उपस्थिति चेक-इन, भुगतान और विवाद आपके स्थानीय डेटाबेस के अंदर सुरक्षित रूप से संग्रहीत हैं और सिग्नल वापस आने पर तुरंत सिंक हो जाएंगे।",
    connectionControl: "कनेक्शन नियंत्रण सिम्युलेटर:",
    loginRegister: "लॉगिन / पंजीकरण",
    logout: "लॉगआउट",
    profile: "प्रोफाइल",

    // Role-specific Nav Tabs
    workerDashboard: "श्रमिक क्षेत्र",
    findJobs: "नौकरी ढूंढें",
    findJobsDesc: "सत्यापित स्थानीय दैनिक-मजदूरी की नौकरियां खोजें",
    myApplications: "मेरे आवेदन",
    checkInRegister: "चेक-इन और उपस्थिति",
    checkInRegisterDesc: "उपस्थिति दर्ज करें और दैनिक मजदूरी ट्रैक करें",
    grievances: "शिकायतें व विवाद",
    grievancesDesc: "मजदूरी/काम के विवाद दर्ज करें और ट्रैक करें",
    financialSavings: "बचत और मजदूरी",
    skillCoach: "कौशल कोच (AI)",
    skillCoachDesc: "AI-निर्देशित व्यावसायिक कौशल विकास",
    helpFaq: "सहायता और FAQ",
    helpFaqDesc: "सुरक्षा सूची और दिशानिर्देश देखें",

    employerDashboard: "ठेकेदार क्षेत्र",
    postJob: "नौकरी पोस्ट करें",
    manageJobs: "नौकरियों का प्रबंधन",
    manageJobsDesc: "नौकरी के कार्य पोस्ट करें और प्रबंधित करें",
    reviewApplications: "प्राप्त आवेदन",
    reviewApplicationsDesc: "आवेदकों को सत्यापित करें और काम पर रखें",
    payoutHistory: "भुगतान इतिहास",

    adminDashboard: "कल्याण पोर्टल",
    platformOverview: "मंच अवलोकन",
    platformOverviewDesc: "विश्लेषण, उपयोगकर्ता और सिंक स्थिति",
    workerRegistry: "श्रमिक रजिस्ट्री",
    employerRegistry: "ठेकेदार रजिस्ट्री",
    platformDisputes: "मंच विवाद",
    platformDisputesDesc: "AI स्क्रीनिंग के साथ विवादों की मध्यस्थता करें",

    // Landing Page Hero
    empoweringDailyWorkers: "एआई के साथ दैनिक वेतन भोगी श्रमिकों का सशक्तिकरण",
    heroTitle: "दैनिक कमाने वालों को निष्पक्ष रोजगार से जोड़ना",
    heroSubtitle: "एम्पोवर्क स्थानीय श्रमिकों, निर्माण बिल्डरों और कल्याण अधिकारियों के लिए बनाया गया एक स्मार्ट डिजिटल पारिस्थितिकी तंत्र है। कौशल पंजीकृत करें, सत्यापित स्थानीय नौकरियों की खोज करें, उपस्थिति दर्ज करें और सुरक्षित दैनिक मजदूरी प्राप्त करें।",
    getStartedButton: "अभी शुरू करें",
    openWelfareOfficerPortal: "कल्याण व्यवस्थापक पोर्टल खोलें",
    whyChooseEmpowork: "एम्पोवर्क को क्यों चुनें?",
    howItWorks: "यह कैसे काम करता है",
    empoweringFeatures: "सशक्त बनाने वाली विशेषताएं",
    disclaimerText: "नोट: वास्तविक समय के भुगतानों को सुरक्षित रूप से संसाधित किया जाता है और श्रम मंत्रालय के दिशानिर्देशों द्वारा समर्थित किया जाता है।",

    // Landing Features
    geoAttendanceTitle: "सत्यापित भू-उपस्थिति",
    geoAttendanceDesc: "दैनिक आगमन के लिए इंटरैक्टिव स्थानिक सत्यापन, समय और पेरोल विसंगतियों को रोकता है।",
    instantWageTitle: "सुरक्षित डिजिटल वॉलेट",
    instantWageDesc: "पारदर्शी समान-दिवस भुगतान लॉग सीधे बचत वॉलेट में निष्पक्ष वेतन सुनिश्चित करते हैं।",
    geminiAdvisorTitle: "जेमिनी एआई विवाद समाधान",
    geminiAdvisorDesc: "दैनिक श्रम विवादों के लिए निष्पक्ष स्वचालित स्क्रीनिंग और पेशेवर मध्यस्थता सुझाव प्रणाली।",
    regionalVoiceTitle: "बहुभाषी वॉयस इनपुट",
    regionalVoiceDesc: "श्रमिकों को हिंदी, कन्नड़ या अंग्रेजी में प्रोफाइल रिकॉर्ड करने, आवेदन दर्ज करने और शिकायतें दर्ज करने की अनुमति देता है।",
    tradeJobsAvailable: "उपलब्ध ट्रेड नौकरियां",
    applyForHighPayingWages: "सत्यापित उच्च दैनिक मजदूरी के लिए आवेदन करें",
    attendanceWagesSavingsHub: "उपस्थिति, मजदूरी और बचत हब",
    verifyShiftsDesc: "अपनी पारियों को सत्यापित करें, वेतन इतिहास को ट्रैक करें और वित्तीय योजना बनाएं",
    shiftsAndLogs: "पारियां और लॉग",
    savingsAndGoals: "बचत और लक्ष्य",
    employerFeedback: "नियोक्ता प्रतिक्रिया और समर्थन",
    officialRatingsDesc: "सत्यापित ठेकेदारों द्वारा काम पूरा होने पर दी गई रेटिंग और प्रतिक्रिया।",
    noJobsFound: "फ़िल्टर से मेल खाती कोई नौकरी नहीं मिली।",
    tryChangingFilters: "अपना ट्रेड चयन या कीवर्ड बदलने का प्रयास करें!",
    quickApply: "ट्रेड प्रोफाइल के साथ त्वरित आवेदन",
    quickContact: "ठेकेदार से त्वरित संपर्क",
    statusPending: "स्थिति: लंबित",
    statusAccepted: "स्थिति: स्वीकृत",
    statusRejected: "स्थिति: अस्वीकृत",
    gpsTracker: "जीपीएस ट्रैकर",
    accessingGps: "सैटेलाइट जीपीएस एक्सेस कर रहा है...",
    activeLat: "सक्रिय अक्षांश",
    gpsOff: "जीपीएस बंद (चालू करने के लिए क्लिक करें)",
    safetyChecklistTitle: "सुरक्षा चेकलिस्ट और मंजूरी",
    submitJobApplication: "नौकरी का आवेदन जमा करें",
    searchJobsPlaceholder: "नौकरियां खोजें...",
    postNewJob: "नई नौकरी पोस्ट करें",
    managePostedJobs: "पोस्ट की गई नौकरियों का प्रबंधन",
    reviewApplicationsTitle: "प्राप्त आवेदनों की समीक्षा",
    payoutLogsTitle: "भुगतान लॉग और वॉलेट ट्रांसफर",
    welfareDisputesTitle: "कल्याण विवाद और शिकायतें",
    tradeRoleRequired: "आवश्यक ट्रेड भूमिका",
    estimatedWage: "अनुमानित दैनिक मजदूरी",
    numberOfSlots: "रिक्तियों की संख्या",
    jobLocation: "नौकरी का स्थान",
    jobDescription: "नौकरी का विवरण",
    createJobAssignment: "नौकरी का असाइनमेंट बनाएं",
    preshiftSafetyTitle: "काम से पहले सुरक्षा ब्रीफिंग",
    financialCoachTitle: "एआई वित्तीय कोच और बचत नियोजक",
    disputeCenterTitle: "श्रम कल्याण विवाद केंद्र",
    dashboard: "डैशबोर्ड",
    dashboardDesc: "अवलोकन और मेट्रिक्स",
    myProfile: "मेरी प्रोफाइल",
    myProfileDesc: "अपने विवरण प्रबंधित करें",
    myApplicationsDesc: "आवेदनों को ट्रैक करें",
    attendance: "उपस्थिति",
    attendanceDesc: "चेक-इन और लॉग",
    myEarnings: "मेरी कमाई",
    myEarningsDesc: "मजदूरी और बचत",
    skillDevelopment: "कौशल विकास",
    skillDevelopmentDesc: "AI कौशल कोच और ट्यूटोरियल",
    myTools: "मेरे उपकरण",
    myToolsDesc: "व्यावसायिक उपकरण",
    notifications: "सूचनाएं",
    notificationsDesc: "अपठित अपडेट और अलर्ट",
    complaintsSupport: "शिकायतें और सहायता",
    complaintsSupportDesc: "विवाद दर्ज करें और ट्रैक करें",
    settings: "सेटिंग्स",
    settingsDesc: "प्राथमिकताएं और सेटअप",
    logoutDesc: "सत्र से बाहर निकलें"
  },
  kn: {
    // Navbar / Global
    brandName: "ಎಂಪ್ಲಾವರ್ಕ್",
    tradeJobsAvailable: "ಲಭ್ಯವಿರುವ ಉದ್ಯೋಗಗಳು",
    applyForHighPayingWages: "ಹೆಚ್ಚಿನ ದಿನಗೂಲಿಗಾಗಿ ಇಂದೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    attendanceWagesSavingsHub: "ಹಾಜರಾತಿ, ಕೂಲಿ ಮತ್ತು ಉಳಿತಾಯ ಹಬ್",
    verifyShiftsDesc: "ನಿಮ್ಮ ಶಿಫ್ಟ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ವೇತನದ ಇತಿಹಾಸವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಆರ್ಥಿಕ ಯೋಜನೆಯನ್ನು ಮಾಡಿ",
    shiftsAndLogs: "ಶಿಫ್ಟ್‌ಗಳು ಮತ್ತು ಲಾಗ್‌ಗಳು",
    savingsAndGoals: "ಉಳಿತಾಯ ಮತ್ತು ಗುರಿಗಳು",
    employerFeedback: "ಮಾಲೀಕರ ವಿಮರ್ಶೆಗಳು ಮತ್ತು ಅನುಮೋದನೆಗಳು",
    officialRatingsDesc: "ಕೆಲಸ ಪೂರ್ಣಗೊಂಡ ನಂತರ ಪರಿಶೀಲಿಸಿದ ಗುತ್ತಿಗೆದಾರರು ಸಲ್ಲಿಸಿದ ಅಧಿಕೃತ ರೇಟಿಂಗ್‌ಗಳು.",
    noJobsFound: "ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದುವ ಯಾವುದೇ ಉದ್ಯೋಗಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    tryChangingFilters: "ನಿಮ್ಮ ಉದ್ಯೋಗ ಕ್ಷೇತ್ರ ಅಥವಾ ಕೀವರ್ಡ್ ಬದಲಾಯಿಸಲು ಪ್ರಯತ್ನಿಸಿ!",
    quickApply: "ಪ್ರೊಫೈಲ್‌ನೊಂದಿಗೆ ತ್ವರಿತ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    quickContact: "ಗುತ್ತಿಗೆದಾರರೊಂದಿಗೆ ತ್ವರಿತ ಸಂಪರ್ಕ",
    statusPending: "ಸ್ಥಿತಿ: ಬಾಕಿ ಉಳಿದಿದೆ",
    statusAccepted: "ಸ್ಥಿತಿ: ಅಂಗೀಕರಿಸಲಾಗಿದೆ",
    statusRejected: "ಸ್ಥಿತಿ: ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
    gpsTracker: "ಜಿಪಿಎಸ್ ಟ್ರ್ಯಾಕರ್",
    accessingGps: "ಉಪಗ್ರಹ ಜಿಪಿಎಸ್ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...",
    activeLat: "ಸಕ್ರಿಯ ಲ್ಯಾಟಿಟ్యూಡ್",
    gpsOff: "ಜಿಪಿಎಸ್ ಆಫ್ ಆಗಿದೆ (ಸಕ್ರಿಯಗೊಳಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ)",
    safetyChecklistTitle: "ಸುರಕ್ಷತಾ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ ಮತ್ತು ಅನುಮತಿ",
    submitJobApplication: "ಉದ್ಯೋಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    searchJobsPlaceholder: "ಕೆಲಸ ಹುಡುಕಿ...",
    postNewJob: "ಹೊಸ ಉದ್ಯೋಗವನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ",
    managePostedJobs: "ಪೋಸ್ಟ್ ಮಾಡಿದ ಕೆಲಸಗಳ ನಿರ್ವಹಣೆ",
    reviewApplicationsTitle: "ಅರ್ಜಿಗಳ ಪರಿಶೀಲನೆ",
    payoutLogsTitle: "ಪಾವತಿ ಲಾಗ್‌ಗಳು ಮತ್ತು ವಾಲೆಟ್ ವರ್ಗಾವಣೆ",
    welfareDisputesTitle: "ಕಲ್ಯಾಣ ವಿವಾದಗಳು ಮತ್ತು ದೂರುಗಳು",
    tradeRoleRequired: "ಅಗತ್ಯವಿರುವ ಉದ್ಯೋಗ ಕ್ಷೇತ್ರ",
    estimatedWage: "ಅಂದಾಜು ದಿನಗೂಲಿ",
    numberOfSlots: "ಖಾಲಿ ಇರುವ ಹುದ್ದೆಗಳು",
    jobLocation: "ಕೆಲಸದ ಸ್ಥಳ",
    jobDescription: "ಕೆಲಸದ ವಿವರಣೆ",
    createJobAssignment: "ಉದ್ಯೋಗ ಪೋಸ್ಟ್ ರಚಿಸಿ",
    preshiftSafetyTitle: "ಶಿಫ್ಟ್ ಪೂರ್ವ ಸುರಕ್ಷತಾ ಮಾಹಿತಿ",
    financialCoachTitle: "AI ಹಣಕಾಸು ತರಬೇತುದಾರ ಮತ್ತು ಉಳಿತಾಯ ಯೋಜಕ",
    disputeCenterTitle: "ಕಾರ್ಮಿಕ ಕಲ್ಯಾಣ ವಿವಾದ ಕೇಂದ್ರ",
    online: "ಆನ್‌ಲೈನ್",
    offline: "ಆಫ್‌ಲೈನ್",
    simulateNoSignal: "ಸಿಗ್ನಲ್ ಇಲ್ಲದಿರುವುದನ್ನು ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ",
    reconnectToCloud: "ಕ್ಲೌಡ್‌ಗೆ ಮರುಸಂಪರ್ಕಿಸಿ",
    networkSyncPortal: "ನೆಟ್‌ವರ್ಕ್ ಮತ್ತು ಸಿಂಕ್ ಪೋರ್ಟಲ್",
    connectedLiveSync: "ಸಂಪರ್ಕಗೊಂಡಿದೆ ಮತ್ತು ಲೈವ್ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ",
    localStorageMode: "ಸ್ಥಳೀಯ ಸಂಗ್ರಹಣೆ ಮೋಡ್",
    excellentCoverage: "ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಹೆಜ್ಜೆಯು (ಹಾಜರಾತಿ ಲಾಗ್‌ಗಳು, ಚೆಕ್-ಇನ್‌ಗಳು, ಕೆಲಸದ ವಿನಂತಿಗಳು ಮತ್ತು ಪಾವತಿಗಳು) ಸುರಕ್ಷಿತ ಕ್ಲೌಡ್ ನೋಂದಣಿಯೊಂದಿಗೆ ಲೈವ್ ಆಗಿ ಸಿಂಕ್ ಆಗುತ್ತದೆ.",
    noReceptionDetected: "ಯಾವುದೇ ಸಿಗ್ನಲ್ ಪತ್ತೆಯಾಗಿಲ್ಲ. ಎಲ್ಲಾ ಹಾಜರಾತಿ ಚೆಕ್-ಇನ್‌ಗಳು, ಪಾವತಿಗಳು ಮತ್ತು ವಿವಾದಗಳನ್ನು ನಿಮ್ಮ ಸ್ಥಳೀಯ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ ಮತ್ತು ಸಿಗ್ನಲ್ ಮರಳಿದಾಗ ತಕ್ಷಣವೇ ಸಿಂಕ್ ಆಗುತ್ತದೆ.",
    connectionControl: "ಸಂಪರ್ಕ ನಿಯಂತ್ರಣ ಸಿಮ್ಯುಲೇಟರ್:",
    loginRegister: "ಲಾಗಿನ್ / ನೋಂದಣಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    profile: "ಪ್ರೊಫೈಲ್",

    // Role-specific Nav Tabs
    workerDashboard: "ಕಾರ್ಮಿಕರ ಸ್ಥಳ",
    findJobs: "ಕೆಲಸ ಹುಡುಕಿ",
    findJobsDesc: "ಸ್ಥಳೀಯ ದೈನಂದಿನ ವೇತನದ ಕೆಲಸಗಳನ್ನು ಹುಡುಕಿ",
    myApplications: "ನನ್ನ ಅರ್ಜಿಗಳು",
    checkInRegister: "ಹಾಜರಾತಿ ದಾಖಲಾತಿ",
    checkInRegisterDesc: "ಹಾಜರಾತಿ ಮತ್ತು ದೈನಂದಿನ ವೇತನ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    grievances: "ದೂರುಗಳು ಮತ್ತು ವಿವಾದಗಳು",
    grievancesDesc: "ವೇತನ/ಕೆಲಸದ ವಿವಾದಗಳನ್ನು ದಾಖಲಿಸಿ",
    financialSavings: "ಉಳಿತಾಯ ಮತ್ತು ಕೂಲಿ",
    skillCoach: "ಕೌಶಲ್ಯ ತರಬೇತುದಾರ (AI)",
    skillCoachDesc: "AI-ಮಾರ್ಗದರ್ಶಿತ ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ",
    helpFaq: "ಸಹಾಯ ಮತ್ತು FAQ",
    helpFaqDesc: "ಸುರಕ್ಷತಾ ಪಟ್ಟಿ ಮತ್ತು ಮಾರ್ಗಸೂಚಿಗಳು",

    employerDashboard: "ಗುತ್ತಿಗೆದಾರರ ಸ್ಥಳ",
    postJob: "ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ",
    manageJobs: "ಕೆಲಸಗಳ ನಿರ್ವಹಣೆ",
    manageJobsDesc: "ಕೆಲಸದ ನಿಯೋಜನೆಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ",
    reviewApplications: "ಬಂದ ಅರ್ಜಿಗಳು",
    reviewApplicationsDesc: "ಅರ್ಜಿದಾರರನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನೇಮಿಸಿ",
    payoutHistory: "ಪಾವತಿ ವಿವರಗಳು",

    adminDashboard: "ಕಲ್ಯಾಣ ಪೋರ್ಟಲ್",
    platformOverview: "ವೇದಿಕೆ ಅವಲೋಕನ",
    platformOverviewDesc: "ವಿಶ್ಲೇಷಣೆ, ಬಳಕೆದಾರರು ಮತ್ತು ಸಿಂಕ್ ಸ್ಥಿತಿ",
    workerRegistry: "ಕಾರ್ಮಿಕರ ನೋಂದಣಿ",
    employerRegistry: "ಗುತ್ತಿಗೆದಾರರ ನೋಂದಣಿ",
    platformDisputes: "ವೇದಿಕೆ ವಿವಾದಗಳು",
    platformDisputesDesc: "AI ತಪಾಸಣೆಯೊಂದಿಗೆ ವಿವಾದಗಳನ್ನು ಬಗೆಹರಿಸಿ",

    // Landing Page Hero
    empoweringDailyWorkers: "ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ (AI) ಯೊಂದಿಗೆ ದಿನಗೂಲಿ ಕಾರ್ಮಿಕರ ಸಬಲೀಕರಣ",
    heroTitle: "ದಿನಗೂಲಿ ಕಾರ್ಮಿಕರಿಗೆ ನ್ಯಾಯಯುತ ಉದ್ಯೋಗದ ಸಂಪರ್ಕ",
    heroSubtitle: "ಎಂಪ್ಲಾವರ್ಕ್ ಸ್ಥಳೀಯ ಕಾರ್ಮಿಕರು, ನಿರ್ಮಾಣ ಬಿಲ್ಡರ್‌ಗಳು ಮತ್ತು ಕಾರ್ಮಿಕ ಕಲ್ಯಾಣ ಅಧಿಕಾರಿಗಳಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಒಂದು ಸ್ಮಾರ್ಟ್ ಡಿಜಿಟಲ್ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯಾಗಿದೆ. ಕೌಶಲ್ಯಗಳನ್ನು ನೋಂದಾಯಿಸಿ, ಪರಿಶೀಲಿಸಿದ ಸ್ಥಳೀಯ ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ, ಹಾಜರಾತಿ ದಾಖಲಿಸಿ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿ ದಿನಗೂಲಿ ಪಡೆಯಿರಿ.",
    getStartedButton: "ಈಗಲೇ ಪ್ರಾರಂಭಿಸಿ",
    openWelfareOfficerPortal: "ಕಲ್ಯಾಣ ನಿರ್ವಾಹಕರ ಪೋರ್ಟಲ್ ತೆರೆಯಿರಿ",
    whyChooseEmpowork: "ಎಂಪ್ಲಾವರ್ಕ್ ಅನ್ನು ಏಕೆ ಆರಿಸಬೇಕು?",
    howItWorks: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    empoweringFeatures: "ಸಬಲೀಕರಣದ ವೈಶಿಷ್ಟ್ಯಗಳು",
    disclaimerText: "ಗಮನಿಸಿ: ನೈಜ-ಸಮಯದ ಪಾವತಿಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಕಾರ್ಮಿಕ ಸಚಿವಾಲಯದ ಮಾರ್ಗಸೂಚಿಗಳಿಂದ ಬೆಂಬಲಿಸಲಾಗುತ್ತದೆ.",

    // Landing Features
    geoAttendanceTitle: "ಪರಿಶೀಲಿಸಿದ ಜಿಯೋ-ಹಾಜರಾತಿ",
    geoAttendanceDesc: "ದೈನಂದಿನ ಆಗಮನಕ್ಕಾಗಿ ಸಂವಾದಾತ್ಮಕ ಪ್ರಾದೇಶಿಕ ಪರಿಶೀಲನೆ, ಸಮಯ ಮತ್ತು ವೇತನದಾರರ ವ್ಯತ್ಯಾಸಗಳನ್ನು ತಡೆಯುತ್ತದೆ.",
    instantWageTitle: "ಸುರಕ್ಷಿತ ಡಿಜಿಟಲ್ ವಾಲೆಟ್",
    instantWageDesc: "ಪಾರದರ್ಶಕ ದಿನದ ಪಾವತಿ ಲಾಗ್‌ಗಳು ನೇರವಾಗಿ ಉಳಿತಾಯ ವಾಲೆಟ್‌ಗಳಿಗೆ ಜಮೆಯಾಗುವುದನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ.",
    geminiAdvisorTitle: "ಜೆಮಿನಿ AI ವಿವಾದ ಪರಿಹಾರ",
    geminiAdvisorDesc: "ದೈನಂದಿನ ಕಾರ್ಮಿಕ ವಿವಾದಗಳಿಗೆ ತಟಸ್ಥ ಸ್ವಯಂಚಾಲಿತ ಪರಿಶೀಲನೆ ಮತ್ತು ವೃತ್ತಿಪರ ಸಂಧಾನ ಸಲಹಾ ವ್ಯವಸ್ಥೆಗಳು.",
    regionalVoiceTitle: "ಬಹುಭಾಷಾ ಧ್ವನಿ ಇನ್‌ಪುಟ್",
    regionalVoiceDesc: "ಕಾರ್ಮಿಕರಿಗೆ ಹಿಂದಿ, ಕನ್ನಡ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಪ್ರೊಫైಲ್ ರೆಕಾರ್ಡ್ ಮಾಡಲು, ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಮತ್ತು ದೂರುಗಳನ್ನು ದಾಖಲಿಸಲು ಅನುಮతಿಸುತ್ತದೆ.",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    dashboardDesc: "ಅವಲೋಕನ ಮತ್ತು ಮೆಟ್ರಿಕ್ಸ್",
    myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    myProfileDesc: "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    myApplicationsDesc: "ಅರ್ಜಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    attendance: "ಹಾಜರಾತಿ",
    attendanceDesc: "ಚೆಕ್-ಇನ್ ಮತ್ತು ಲಾಗ್‌ಗಳು",
    myEarnings: "ನನ್ನ ಗಳಿಕೆ",
    myEarningsDesc: "ವೇತನ ಮತ್ತು ಉಳಿತಾಯ",
    skillDevelopment: "ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ",
    skillDevelopmentDesc: "AI ಕೌಶಲ್ಯ ತರಬೇತುದಾರ ಮತ್ತು ಟ್ಯುಟೋರಿಯಲ್",
    myTools: "ನನ್ನ ಪರಿಕರಗಳು",
    myToolsDesc: "ವೃತ್ತಿಪರ ಪರಿಕರಗಳು",
    notifications: "ಸೂಚನೆಗಳು",
    notificationsDesc: "ಓದದ ನವೀಕರಣಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು",
    complaintsSupport: "ದೂರುಗಳು ಮತ್ತು ಬೆಂಬಲ",
    complaintsSupportDesc: "ದೂರುಗಳನ್ನು ದಾಖಲಿಸಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    settings: "ಸಂಯೋಜನೆಗಳು",
    settingsDesc: "ಆದ್ಯತೆಗಳು ಮತ್ತು ಕಾನ್ಫಿಗರೇಶನ್",
    logoutDesc: "ಸಶನ್‌ನಿಂದ ಲಾಗ್ ಔಟ್ ಮಾಡಿ"
  },
  te: {
    // Navbar / Global
    brandName: "ఎంపోవర్క్",
    online: "ఆన్‌లైన్",
    offline: "ఆఫ్‌లైన్",
    simulateNoSignal: "సిగ్నల్ లేనట్లు అనుకరించు",
    reconnectToCloud: "క్లాウドకి మళ్లీ కనెక్ట్ చేయి",
    networkSyncPortal: "నెట్‌వర్క్ & సింక్ పోర్టల్",
    connectedLiveSync: "కనెక్ట్ చేయబడింది & లైవ్ సింక్ అవుతోంది",
    localStorageMode: "లోకల్ స్టోరేజ్ మోడ్",
    excellentCoverage: "మీ డిజిటల్ హాజరు, చెక్-ఇన్‌లు, ఉద్యోగ అభ్యర్థనలు మరియు ప్లాట్‌ఫారమ్ వివరాలు క్లౌడ్ రిజిస్ట్రీతో సురక్షితంగా లైవ్ సింక్ అవుతాయి.",
    noReceptionDetected: "సిగ్నల్ లేదు. మీ హాజరు, చెల్లింపులు మరియు వివాదాలు లోకల్ డేటాబేస్‌లో సురక్షితంగా సేవ్ చేయబడతాయి. సిగ్నల్ రాగానే ఆటోమేటిక్‌గా సింక్ అవుతాయి.",
    connectionControl: "కనెక్షన్ నియంత్రణ సిమ్యులేటర్:",
    loginRegister: "లాగిన్ / రిజిస్ట్రేషన్",
    logout: "లాగ్ అవుట్",
    profile: "ప్రొఫైల్",

    // Role-specific Nav Tabs
    workerDashboard: "కార్మికుల విభాగం",
    findJobs: "ఉద్యోగాలు వెతకండి",
    findJobsDesc: "ధృవీకరించబడిన స్థానిక రోజువారీ వేతన ఉద్యోగాలను కనుగొనండి",
    myApplications: "నా అప్లికేషన్లు",
    checkInRegister: "హాజరు నమోదు",
    checkInRegisterDesc: "హాజరును నమోదు చేయండి మరియు రోజువారీ వేతనాలను ట్రాక్ చేయండి",
    grievances: "ఫిర్యాదులు & వివాదాలు",
    grievancesDesc: "వేతనం/పని వివాదాలను నమోదు చేయండి మరియు ట్రాక్ చేయండి",
    financialSavings: "పొదుపు & వేతనాలు",
    skillCoach: "నైపుణ్య శిక్షకుడు (AI)",
    skillCoachDesc: "AI-ఆధారిత వృత్తిపరమైన నైపుణ్యాల అభివృద్ధి",
    helpFaq: "సహాయం & FAQ",
    helpFaqDesc: "భద్రతా జాబితాలు మరియు సూచనలను వీక్షించండి",

    employerDashboard: "కాంట్రాక్టర్ విభాగం",
    postJob: "ఉద్యోగాన్ని పోస్ట్ చేయి",
    manageJobs: "ఉద్యోగాల నిర్వహణ",
    manageJobsDesc: "ఉద్యోగ నియామకాలను పోస్ట్ చేయండి మరియు నిర్వహించండి",
    reviewApplications: "అప్లికేషన్లు",
    reviewApplicationsDesc: "దరఖాస్తుదారులను ధృవీకరించండి మరియు సిబ్బందిని నియమించుకోండి",
    payoutHistory: "చెల్లింపుల చరిత్ర",

    adminDashboard: "సంక్షేమ పోర్టల్",
    platformOverview: "ప్లాట్‌ఫారమ్ అవలోకనం",
    platformOverviewDesc: "విశ్లేషణలు, వినియోగదారులు మరియు సమకాలీకరణ స్థితి",
    workerRegistry: "కార్మికుల రిజిస్ట్రీ",
    employerRegistry: "యజమానుల రిజిస్ట్రీ",
    platformDisputes: "ప్లాట్‌ఫారమ్ వివాదాలు",
    platformDisputesDesc: "AI స్క్రీనింగ్‌తో వివాదాలను పరిష్కరించండి",

    // Landing Page Hero
    empoweringDailyWorkers: "AI తో రోజువారీ వేతన కార్మికుల సాధికారత",
    heroTitle: "రోజువారీ సంపాదకులకు సరైన ఉపాధిని కల్పించడం",
    heroSubtitle: "ఎంపోవర్క్ అనేది కార్మికులు, నిర్మాణ బిల్డర్లు మరియు సంక్షేమ అధికారుల కోసం రూపొందించబడిన ఒక స్మార్ట్ డిజిటల్ వేదిక. మీ నైపుణ్యాలను నమోదు చేసుకోండి, ధృవీకరించబడిన స్థానిక ఉద్యోగాల కోసం వెతకండి, హాజరును నమోదు చేయండి మరియు రోజువారీ వేతనాలను సురక్షితంగా పొందండి.",
    getStartedButton: "ఇప్పుడే ప్రారంభించండి",
    openWelfareOfficerPortal: "సంక్షేమ అధికారి పోర్టల్ తెరువు",
    whyChooseEmpowork: "ఎంపోవర్క్‌ను ఎందుకు ఎంచుకోవాలి?",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    empoweringFeatures: "ముఖ్యమైన ఫీచర్లు",
    disclaimerText: "గమనిక: నిజ-సమయ చెల్లింపులు సురక్షితంగా ప్రాసెస్ చేయబడతాయి మరియు కార్మిక మంత్రిత్వ శాఖ మార్గదర్శకాలకు అనుగుణంగా ఉంటాయి.",

    // Landing Features
    geoAttendanceTitle: "ధృవీకరించబడిన జియో-హాజరు",
    geoAttendanceDesc: "రోజువారీ రాకలను ధృవీకరించడానికి జియో-హాజరు, సమయాలు మరియు జీతాల తారతమ్యాలను నివారిస్తుంది.",
    instantWageTitle: "సురక్షిత డిజిటల్ వాలెట్లు",
    instantWageDesc: "పారదర్శకమైన రోజువారీ చెల్లింపుల వివరాలు నేరుగా మీ వాలెట్‌కు జమ చేయబడతాయి.",
    geminiAdvisorTitle: "జెమిని AI వివాద పరిష్కారం",
    geminiAdvisorDesc: "రోజువారీ కార్మిక వివాదాల కోసం తటస్థ మరియు ఆటోమేటెడ్ సహాయక వ్యవస్థ.",
    regionalVoiceTitle: "బహుభాషా వాయిస్ ఇన్‌పుట్",
    regionalVoiceDesc: "కార్మికులు తమ వివరాలను తెలుగు, హిందీ, కన్నడ లేదా ఇంగ్లీషులో వాయిస్ ద్వారా నమోదు చేసుకోవచ్చు.",
    tradeJobsAvailable: "అందుబాటులో ఉన్న ఉద్యోగాలు",
    applyForHighPayingWages: "ధృవీకరించబడిన అధిక దినసరి వేతన ఉద్యోగాల కోసం దరఖాస్తు చేసుకోండి",
    attendanceWagesSavingsHub: "హాజరు, వేతనాలు & పొదుపు కేంద్రం",
    verifyShiftsDesc: "మీ షిఫ్టులను ధృవీకరించుకోండి, జీతాల చరిత్రను ట్రాక్ చేయండి మరియు ఆర్థిక ప్రణాళికను సిద్ధం చేసుకోండి",
    shiftsAndLogs: "షిఫ్టులు & వివరాలు",
    savingsAndGoals: "పొదుపులు & లక్ష్యాలు",
    employerFeedback: "యజమానుల రేటింగ్‌లు మరియు అభిప్రాయాలు",
    officialRatingsDesc: "పని పూర్తయిన తర్వాత ధృవీకరించబడిన బిల్డర్ కాంట్రాక్టర్ల ద్వారా అందించబడిన రేటింగ్‌లు.",
    noJobsFound: "ఫిల్టర్లకు సరిపోయే ఉద్యోగాలు ఏవీ లేవు.",
    tryChangingFilters: "మీ పని రకం లేదా కీవర్డ్ మార్చడానికి ప్రయత్నించండి!",
    quickApply: "ప్రొఫైల్‌తో త్వరిత దరఖాస్తు",
    quickContact: "యజమానితో త్వరిత సంప్రదింపు",
    statusPending: "స్థితి: పెండింగ్",
    statusAccepted: "స్థితి: ఆమోదించబడింది",
    statusRejected: "స్థితి: తిరస్కరించబడింది",
    gpsTracker: "GPS ట్రాకర్",
    accessingGps: "శాటిలైట్ GPS యాక్సెస్ చేస్తోంది...",
    activeLat: "యాక్టివ్ లాటిట్యూడ్",
    gpsOff: "GPS ఆఫ్ చేయబడింది (ఆన్ చేయడానికి క్లిక్ చేయండి)",
    safetyChecklistTitle: "భద్రతా తనిఖీ మరియు అనుమతి",
    submitJobApplication: "ఉద్యోగ దరఖాస్తును సమర్పించండి",
    searchJobsPlaceholder: "ఉద్యోగాల కోసం వెతకండి...",
    postNewJob: "కొత్త ఉద్యోగాన్ని పోస్ట్ చేయి",
    managePostedJobs: "పోస్ట్ చేసిన ఉద్యోగాల నిర్వహణ",
    reviewApplicationsTitle: "దరఖాస్తుల సమీక్ష",
    payoutLogsTitle: "చెల్లింపుల చరిత్ర & వాలెట్ బదిలీ",
    welfareDisputesTitle: "సంక్షేమ వివాదాలు & ఫిర్యాదులు",
    tradeRoleRequired: "కావలసిన పని రకం",
    estimatedWage: "అంచనా వేసిన దినసరి వేతనం",
    numberOfSlots: "ఖాళీల సంఖ్య",
    jobLocation: "పని ప్రదేశం",
    jobDescription: "ఉద్యోగ వివరణ",
    createJobAssignment: "ఉద్యోగ అవకాశాన్ని సృష్టించండి",
    preshiftSafetyTitle: "పని ప్రారంభానికి ముందు భద్రతా సూచనలు",
    financialCoachTitle: "AI ఫైనాన్షియల్ కోచ్ & సేవింగ్స్ ప్లానర్",
    disputeCenterTitle: "కార్మిక సంక్షేమ వివాదాల కేంద్రం",
    dashboard: "డ్యాష్‌బోర్డ్",
    dashboardDesc: "అవలోకనం & కొలతలు",
    myProfile: "నా ప్రొఫైల్",
    myProfileDesc: "మీ వివరాలను నిర్వహించండి",
    myApplicationsDesc: "అప్లికేషన్లను ట్రాక్ చేయండి",
    attendance: "హాజరు",
    attendanceDesc: "చెక్-ఇన్ & వివరాలు",
    myEarnings: "నా సంపాదన",
    myEarningsDesc: "వేతనాలు & పొదుపులు",
    skillDevelopment: "నైపుణ్యాభివృద్ధి",
    skillDevelopmentDesc: "AI స్కిల్ కోచ్ & ట్యుటోరియల్స్",
    myTools: "నా ఉపకరణాలు",
    myToolsDesc: "వృత్తిపరమైన పరికరాలు",
    notifications: "నోటిఫికేషన్లు",
    notificationsDesc: "చదవని నవీకరణలు & హెచ్చరికలు",
    complaintsSupport: "ఫిర్యాదులు & మద్దతు",
    complaintsSupportDesc: "వివాదాలను నమోదు చేయండి & ట్రాక్ చేయండి",
    settings: "సెట్టింగులు",
    settingsDesc: "ప్రాధాన్యతలు & సెటప్",
    logoutDesc: "సెషన్ నుండి లాగ్ అవుట్ అవ్వండి"
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    return (localStorage.getItem("empowork_language") as LanguageCode) || "en";
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem("empowork_language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
